### PR TITLE
Adding java class to add empty page functionality

### PR DESCRIPTION
**Pull request by RamDixitErra**

### CODE REVIEW

**Review by RavaliSatla — APPROVED** [review]
As discussed over call, result came out in an excellent way than suggested. This functionality not only adds as an additional star to the suit but also an end user attractor. This is most simplest form to add a page functionality. Looks as per the requirement. Approving it!

**Comment by RamDixitErra** [comment]
Hey Ravali, it's corrected now (extension name), Could you please check?

**Comment by RavaliSatla** [comment]
Yeah Verified, It's Fine. And Could you please add the comments as well for this code

**Comment by RamDixitErra** [comment]
Im on it right now,  and going to add comments for all the functionality code pages i have written. need to do the programming by contract. Let me if I miss anything to mention.

**Pull request merged**
