### PR TITLE
Adding UI Button for Protect Password and also adding method in controller file for protect password functionality

### PR DESCRIPTION
**Pull request by RavaliSatla**

### CODE REVIEW

**Review by rahul-satla — COMMENTED** [review]
There are few conflicts in this file, Please resolve the conflicts and do the proper indentation. I will recheck once you resolve them.

**Comment by RavaliSatla** [comment]
> There are few conflicts in this file, Please resolve the conflicts and do the proper indentation. I will recheck once you resolve them.

okay

**Comment by RavaliSatla** [comment]
I resolved all the conflicts and did proper indentation as well

**Comment by rahul-satla** [comment]
This looks proper now, Merging the pull request

**Pull request merged**
